@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Контекстная диаграмма текущей архитектуры розничного предприятия

Person(customer, "Клиент", "Покупатель в интернет-магазине или офлайн-точке")
Person(manager, "Менеджер", "Управляет операционной деятельностью")

System(online_shop, "Интернет-магазин", "B2C web + мобильное приложение")
System(crm, "CRM", "Управление клиентами и заявками")
System(wms, "WMS", "Управление складом")
System(ones_trade, "1С Торговля", "Оперативный учёт продаж и товаров")
System(ones_sd, "1С Денежные средства", "Учёт денежных потоков")
System(ones_doc, "1С Документооборот", "Согласование документов")

System_Ext(social, "BrandAnalytics", "Мониторинг соцмедиа (отзывы, упоминания)")

Rel(customer, online_shop, "Делает заказ", "HTTPS")
Rel(customer, crm, "Обращается в поддержку", "телефон/email")
Rel(online_shop, ones_trade, "Передаёт заказы", "REST API")
Rel(online_shop, crm, "Синхронизирует клиентов", "JDBC")
Rel(ones_trade, wms, "Отправляет задания на сборку", "файловый обмен")
Rel(ones_trade, ones_sd, "Формирует проводки", "JDBC")
Rel(ones_trade, ones_doc, "Генерирует счета-фактуры", "JDBC")
Rel(manager, ones_trade, "Просматривает отчёты")
Rel(manager, crm, "Анализирует клиентов")
Rel(manager, wms, "Контролирует остатки")

@enduml